run:
  timeout: 5m

linters-settings:
  gofmt:
    simplify: true
  gci:
    sections:
    - Standard
    - Default
    - Prefix(github.com/Shopify/zk)

linters:
  disable-all: true
  enable:
  # Defaults
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - unused
  
  # Extras
  - gofmt
  - unconvert
  - gci
  - revive
  - stylecheck
  - whitespace
